### ISSUE TITLE
Problem in /show_rated

### ISSUE THREAD

**Issue by tozangezan** [kazuyalegrey/TaBarksCo#10]
Calling `/show_rated muscle growth` causes the response that says the query is ambiguous (between "muscle growth" and "hyper muscle growth"). Even if you choose `/show_rated muscle growth` out of two choices, you are given the same response.

**Comment by kazuyalegrey** [comment]
It's a bug.
I've fixed it in `/whats` function but forgot about/show_rated.
Will fix tonight!

**Comment by kazuyalegrey** [comment]
Confirmed to be fixed!
